name: EVM Node RPC CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "evm/**"
  pull_request:
    branches:
      - main
    paths:
      - "evm/**"

defaults:
  run:
    working-directory: ./evm

env:
  IMAGE_NAME: evm_net
  THE_GRAPH_NAME: graphprotocol/graph-node
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish image

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./evm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q) --force
            docker system prune -a --volumes -f
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            docker run -d --name=${{ env.IMAGE_NAME }} -p 8545:8545 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            cd ./the_graph/
            rm -rf ./data/
            docker compose up -d
            docker ps
